proxy:
  title: Open Analytics Shiny Proxy (xxbranchxx)
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  container-backend: kubernetes
  kubernetes:
    internal-networking: true
    image-pull-policy: Always
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  
  - id: dash_simple
    display-name: Hello Dash
    description: Application which demonstrates the basics of a Dash app
    port: 8050
    container-cmd: ["gunicorn", "--bind", "0.0.0.0:8050","app1:server"]
    container-image: magralo95/shinyproxy-demo-dash

  - id: pokedex
    display-name: Pokedex
    description: Application which demonstrates a more complex shinyapp that runs with an image that we build in the deployment process
    container-cmd: ["R", "-e", "shiny::runApp('/root/pokedex')"]
    container-image: gcr.io/xxprojidxx/xxshinyappsxx:xxbranchxx
  
  - id: dash_udi
    display-name: Hello Dash (with my image)
    description: Application which demonstrates the basics of a Dash app that runs with an image that we build in the deployment process
    port: 8050
    container-cmd: ["gunicorn", "--bind", "0.0.0.0:8050","app1:server"]
    container-image: gcr.io/xxprojidxx/xxdashappsxx:xxbranchxx

logging:
  file:
    shinyproxy.log