apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinyproxy
spec:
  selector:
    matchLabels:
      run: shinyproxy
  replicas: 1
  template:
    metadata:
      labels:
        run: shinyproxy
    spec:
      containers:
      - name: shinyproxy
        image: gcr.io/xxprojidxx/xxshinyproxyxx
        imagePullPolicy: Always
        ports:
        - containerPort: 8080